<?php
/**
 * @name		Prefixr API Helper
 * @author		Bo Thomsen
 * @company		Illution
 * @package		CSS Prefixr
 * @version 	1.2
 * @url			http://illution.dk
 * @license		MIT License
 * @date		16/12-2011
 */
class Prefixr{
	
	/* Internals */
	private $Prefixr_API_Url = 'http://prefixr.com/api/index.php'; //The url to the Prefixr api
	
	/* The constructor
	| @access public
	*/
	public function Prefixr(){
		
	}
	
	/* The function to get the content of the prefixed css from Prefixr parsed in $CSS 
	| @param {String}	$CSS - The CSS that needs to be sent to the prefixer API
	| @return {String}	- Returns the prefixed CSS
	| @access public
	*/
	public function Generate($CSS = NULL){
		if(!is_null($CSS)){
			$Data = @file_get_contents($this->Prefixr_API_Url.'?css='.urlencode($CSS));
		}
		return ($Data != '')? $Data : FALSE;
	}
	
	/* A function to request the prefixed CSS of $CSS and Save it to the specified Filename in $File
	| @param {String}	$CSS - The CSS that should be sent to Prefixr
	| @param {String}	$File - The filename of the file the result should be saved to
	| @return {Boolean}	- Returns if the operation was succeded
	| @access public
	*/
	public function Save_To_File($CSS = NULL,$File = NULL){
		if(!is_null($File) && !is_null($CSS)){
			$Data = self::Generate($CSS);
			if(file_exists($File)){
				$Data = '/* Generated by Prefixr, Prefixr.com */'.$Data;
				return file_put_contents($File,$Data);
			}
		}
	}
}
?>